IS17/Models/WorkHistory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS17.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WorkHistory
    {
        public int WorkHistoryId { get; set; }
        [Required]
        [Display(Name = "M#")]
        public string MNumber { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Company Name")]
        public int CompanyId { get; set; }
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }
        [Display(Name = "Job Title")]
        public Nullable<int> TitleId { get; set; }
        [Display(Name = "Job Title")]
        public string TitleName { get; set; }
        [Display(Name = "Job Start Date")]
        public System.DateTime StartDate { get; set; }
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> FTE { get; set; }
        public Nullable<int> Compensation { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual StudentAlum StudentAlum { get; set; }
        public virtual Title Title { get; set; }
    }
}

IS17/Controllers/WorkHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IS17.Models;

namespace IS17.Controllers
{
    public class WorkHistoriesController : Controller
    {
        private IS17_DBEntities db = new IS17_DBEntities();

        // GET: WorkHistories
        //public ActionResult Index()
        //{
        //    var workHistories = db.WorkHistories.Include(w => w.Company).Include(w => w.StudentAlum).Include(w => w.Title);
        //    return View(workHistories.ToList());
        //}

        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "CompanyName")
            {
                return View(db.WorkHistories.Where(x => x.CompanyName.StartsWith(search) || search == null).ToList());
            }
            else
            {
                return View(db.WorkHistories.Where(x => x.TitleName.StartsWith(search) || search == null).ToList());
            }
        }


        // GET: WorkHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkHistory workHistory = db.WorkHistories.Find(id);
            if (workHistory == null)
            {
                return HttpNotFound();
            }
            return View(workHistory);
        }

        // GET: WorkHistories/Create
        public ActionResult Create()
        {
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName");
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName");
            ViewBag.TitleId = new SelectList(db.Titles, "TitleId", "TitleName");
            return View();
        }

        // POST: WorkHistories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WorkHistoryId,MNumber,LastName,CompanyId,CompanyName,TitleId,TitleName,StartDate,EndDate,FTE,Compensation")] WorkHistory workHistory)
        {
            if (ModelState.IsValid)
            {
                db.WorkHistories.Add(workHistory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", workHistory.CompanyId);
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName", workHistory.MNumber);
            ViewBag.TitleId = new SelectList(db.Titles, "TitleId", "TitleName", workHistory.TitleId);
            return View(workHistory);
        }

        // GET: WorkHistories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkHistory workHistory = db.WorkHistories.Find(id);
            if (workHistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", workHistory.CompanyId);
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName", workHistory.MNumber);
            ViewBag.TitleId = new SelectList(db.Titles, "TitleId", "TitleName", workHistory.TitleId);
            return View(workHistory);
        }

        // POST: WorkHistories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorkHistoryId,MNumber,LastName,CompanyId,CompanyName,TitleId,TitleName,StartDate,EndDate,FTE,Compensation")] WorkHistory workHistory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workHistory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", workHistory.CompanyId);
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName", workHistory.MNumber);
            ViewBag.TitleId = new SelectList(db.Titles, "TitleId", "TitleName", workHistory.TitleId);
            return View(workHistory);
        }

        // GET: WorkHistories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkHistory workHistory = db.WorkHistories.Find(id);
            if (workHistory == null)
            {
                return HttpNotFound();
            }
            return View(workHistory);
        }

        // POST: WorkHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkHistory workHistory = db.WorkHistories.Find(id);
            db.WorkHistories.Remove(workHistory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IS17/Views/WorkHistories/Create.cshtml
@model IS17.Models.WorkHistory

@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Work History</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.MNumber, "MNumber", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("MNumber", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.MNumber, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.TitleId, "TitleId", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TitleId", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TitleId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.TitleName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.TitleName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.TitleName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.FTE, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.FTE, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.FTE, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Compensation, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Compensation, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Compensation, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")

	@Scripts.Render("~/bundles/jqueryui")
	@Styles.Render("~/Content/cssjqryUi")
	<script type="text/javascript">
    $(document).ready(function () {
    $('input[type=datetime]').datepicker({
    dateFormat: "dd/M/yy",
    changeMonth: true,
    changeYear: true,
    yearRange: "-60:+0"
    });
    });
	</script>

}

IS17/Views/WorkHistories/Delete.cshtml
@model IS17.Models.WorkHistory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FTE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compensation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Compensation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentAlum.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAlum.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title.TitleName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IS17/Views/WorkHistories/Details.cshtml
@model IS17.Models.WorkHistory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WorkHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FTE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compensation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Compensation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentAlum.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAlum.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title.TitleName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WorkHistoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IS17/Views/WorkHistories/Edit.cshtml
@model IS17.Models.WorkHistory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WorkHistoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.MNumber, "MNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TitleId, "TitleId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TitleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TitleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TitleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TitleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FTE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FTE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Compensation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compensation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compensation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS17/Views/WorkHistories/Index.cshtml
@model IEnumerable<IS17.Models.WorkHistory>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Work History List</h2>

<p>
	@Html.ActionLink("Add New", "Create", routeValues: null, htmlAttributes: new { @class = "btn btn-info btn-justified ", @role = "button" })
</p>

<p>
	@using (Html.BeginForm("Index", "WorkHistories", FormMethod.Get))
	{
		<b>Search By:</b>
		@Html.RadioButton("searchBy", "CompanyName", true) <text>Company Name</text>
		@Html.RadioButton("searchBy", "TitleName") <text>Title Name</text>
		<br />
		@Html.TextBox("search")<input type="submit" value="Search" />
	}
</p>

<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.LastName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.CompanyName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.TitleName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.StartDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.EndDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FTE)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Compensation)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Company.CompanyName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.StudentAlum.LastName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Title.TitleName)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.CompanyName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.TitleName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.StartDate)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.EndDate)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.FTE)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Compensation)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Company.CompanyName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.StudentAlum.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Title.TitleName)
			</td>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = item.WorkHistoryId }) |
				@Html.ActionLink("Details", "Details", new { id = item.WorkHistoryId }) |
				@Html.ActionLink("Delete", "Delete", new { id = item.WorkHistoryId })
			</td>
		</tr>
	}

</table>


@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")

	@Scripts.Render("~/bundles/jqueryui")
	@Styles.Render("~/Content/cssjqryUi")
	<script type="text/javascript">
        // #clearDates is a button to clear the datepickers
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                setDate: null,
                showButtonPanel: true,
                closeText: 'Clear',
                onClose: function (dateText, obj) {
                    if ($(window.event.srcElement).hasClass('ui-datepicker-close'))
                        $("#txtCalendar").val('');
                },
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",

            });
        });
	</script>

}