IS17/Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IS17.Models;

namespace IS17.Controllers
{
    public class InterviewsController : Controller
    {
        private IS17_DBEntities db = new IS17_DBEntities();

        // GET: Interviews
        //public ActionResult Index()
        //{
        //    var interviews = db.Interviews.Include(i => i.StudentAlum);
        //    return View(interviews.ToList());
        //}


        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "InterviewCompany")
            {
                return View(db.Interviews.Where(x => x.InterviewCompany.StartsWith(search) || search == null).ToList());
            }
            else
            {
                return View(db.Interviews.Where(x => x.MNumber.EndsWith(search) || search == null).ToList());
            }
        }



        // GET: Interviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = db.Interviews.Find(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            return View(interview);
        }

        // GET: Interviews/Create
        public ActionResult Create()
        {
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName");
            return View();
        }

        // POST: Interviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InterviewId,MNumber,InterviewCompany,InterviewDate,Offer")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                db.Interviews.Add(interview);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName", interview.MNumber);
            return View(interview);
        }

        // GET: Interviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = db.Interviews.Find(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName", interview.MNumber);
            return View(interview);
        }

        // POST: Interviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InterviewId,MNumber,InterviewCompany,InterviewDate,Offer")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                db.Entry(interview).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MNumber = new SelectList(db.StudentAlums, "MNumber", "LastName", interview.MNumber);
            return View(interview);
        }

        // GET: Interviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = db.Interviews.Find(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            return View(interview);
        }

        // POST: Interviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Interview interview = db.Interviews.Find(id);
            db.Interviews.Remove(interview);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IS17/Views/Interviews/Create.cshtml
@model IS17.Models.Interview

@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Interviews</h2>
<h3>Scheduled or Conducted</h3>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.MNumber, "MNumber", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("MNumber", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.MNumber, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.InterviewCompany, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.InterviewCompany, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.InterviewCompany, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.InterviewDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.InterviewDate, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Offer, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<div class="checkbox">
					@Html.EditorFor(model => model.Offer)
					@Html.ValidationMessageFor(model => model.Offer, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-success" />
				@Html.ActionLink("Back to List", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-info btn-justified ", @role = "button" })
			</div>
		</div>
	</div>
}


@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/jqueryui")
	@Styles.Render("~/Content/cssjqryUi")
	<script type="text/javascript">
    $(document).ready(function () {
    $('input[type=datetime]').datepicker({
    dateFormat: "dd/M/yy",
    changeMonth: true,
    changeYear: true,
    yearRange: "-60:+0"
    });
    });
	</script>

}

IS17/Views/Interviews/Delete.cshtml
@model IS17.Models.Interview

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InterviewCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentAlum.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAlum.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IS17/Views/Interviews/Details.cshtml
@model IS17.Models.Interview

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InterviewCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentAlum.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAlum.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.InterviewId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IS17/Views/Interviews/Edit.cshtml
@model IS17.Models.Interview

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Interview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InterviewId)

        <div class="form-group">
            @Html.LabelFor(model => model.MNumber, "MNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewCompany, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewCompany, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Offer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Offer)
                    @Html.ValidationMessageFor(model => model.Offer, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS17/Views/Interviews/Index.cshtml
@model IEnumerable<IS17.Models.Interview>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Interview List</h2>

<p>
	@Html.ActionLink("Add New", "Create", routeValues: null, htmlAttributes: new { @class = "btn btn-info btn-justified ", @role = "button" })
</p>

<p>
	@using (Html.BeginForm("Index", "Interviews", FormMethod.Get))
	{
		<b>Search By:</b><br />
		@Html.RadioButton("searchBy", "InterviewCompany", true) <text>Company Name</text>
		@Html.RadioButton("searchBy", "InterviewDate", true) <text>Interview Date</text>
		<br />
		@Html.TextBox("search")<input type="submit" value="Search" />
	}
</p>

<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.InterviewCompany)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.InterviewDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Offer)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.StudentAlum.LastName)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.InterviewCompany)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.InterviewDate)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Offer)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.StudentAlum.LastName)
			</td>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = item.InterviewId }) |
				@Html.ActionLink("Details", "Details", new { id = item.InterviewId }) |
				@Html.ActionLink("Delete", "Delete", new { id = item.InterviewId })
			</td>
		</tr>
	}

</table>


@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")

	@Scripts.Render("~/bundles/jqueryui")
	@Styles.Render("~/Content/cssjqryUi")
	<script type="text/javascript">
        // #clearDates is a button to clear the datepickers
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                setDate: null,
                showButtonPanel: true,
                closeText: 'Clear',
                onClose: function (dateText, obj) {
                    if ($(window.event.srcElement).hasClass('ui-datepicker-close'))
                        $("#txtCalendar").val('');
                },
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",

            });
        });
	</script>

}